// <auto-generated />
using System;
using MaterialUI.MVVM.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaterialUI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MaterialUI.MVVM.Model.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
